### ISSUE TITLE
Warn players this diverges from CE and may potentially be save incompatible with future CE releases

### ISSUE THREAD

**Issue by JonnyNova** [kpqi5858/CombatExtended#21]

**Comment by kpqi5858** [comment]
Ok, show on mod post's description

**Comment by kpqi5858** [comment]
Edited steam mod posts.

**Comment by kpqi5858** [comment]
Show an message warning on Rimworld startup once

**Comment by JonnyNova** [comment]
Perfect. Still highly recommend rebasing against current CE Development branch though.
