### ISSUE TITLE
when reloading a weapon with no ammo the weapon unequips itself

### ISSUE THREAD

**Issue by kleiner-sentry** [kpqi5858/CombatExtended#40]

**Comment by kpqi5858** [comment]
That's original features of CE

**Comment by kleiner-sentry** [comment]
Well then thats a bad feature. Its really annoying trying to reload a gun in the heat of battle only for the pawn to have the wrong ammo type and unequip it immediately forcing me to drop it, and then requip it again.

Also, can you make the ammo types guns can accept less strict, and maybe even make the ammo craftable? I know that the strict ammo types is a feature in the game but it would be a good quality-of-life feature.

**Comment by kpqi5858** [comment]
Firing wrong caliber? And ammo is already craftable in ammo workbench (i think) if u finish certain research.
Reloading on no ammo should not drop gun, put back in inventory (if has space)

**Comment by kleiner-sentry** [comment]
Oh ok. Well it would be nice if the mod wouldn't do that.
